// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AuditsController from "./audits_controller"
application.register("audits", AuditsController)

import BookController from "./book_controller"
application.register("book", BookController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import FormController from "./form_controller"
application.register("form", FormController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import UsersController from "./users_controller"
application.register("users", UsersController)
