version: "3.7"
services:

  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: medplan_development
      POSTGRES_USER: medplan
      POSTGRES_PASSWORD: MyPassword

  redis:
    image: redis:6.2.6

  cas-mock-server:
    image: apereo/cas
    volumes:
      - ./docker/cas:/etc/cas/
    ports:
      - 8080:8080

  web:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'cas-mock-server'
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: >
      sh -c "EDITOR='cat' bin/rails credentials:edit ; bin/rails db:migrate db:seed assets:precompile && bin/rails s -p 8020 -b 0.0.0.0"
    ports:
      - 8020:8020
    environment:
      RAILS_CAS_URL: http://cas-mock-server:8080/cas
      RAILS_DATABASE_URL: postgres://medplan:MyPassword@postgres/medplan_development
      RAILS_ENV: production
      RAILS_GROUP_MENU: true
      RAILS_REDIS_URL: redis://redis:6379/1

    links:
      - postgres
      - redis
      - cas-mock-server
