version: "3.7"
services:

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432

  redis:
    image: redis:alpine

  cas-mock-server:
    image: apereo/cas-initializr:0.0.36
    volumes:
      - ./.docker/cas:/etc/cas/
    ports:
      - 8080:8080

  web:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'cas-mock-server'
    build:
      context: .
      args:
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
    command: >
      bash -c "EDITOR='cat' && bin/rails credentials:edit && bundle exec rails db:migrate db:truncate db:seed assets:precompile && bundle exec rails s -p 8020 -b 0.0.0.0"
    ports:
      - 8020:8020
    environment:
      RAILS_CAS_URL: ${RAILS_CAS_URL}
      RAILS_DATABASE_URL: ${RAILS_DATABASE_URL}
      RAILS_ENV: ${RAILS_ENV}
      RAILS_AUTHENTICATOR: ${RAILS_AUTHENTICATOR}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
      RAILS_GROUP_MENU: ${RAILS_GROUP_MENU}
      RAILS_REDIS_URL: ${RAILS_REDIS_URL}
    links:
      - postgres
      - redis
      - cas-mock-server
