version: "3.7"
services:

  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: medplan_development
      POSTGRES_USER: medplan
      POSTGRES_PASSWORD: MyPassword

  redis:
    image: redis:7-alpine

  cas-mock-server:
    image: apereo/cas-initializr:0.0.36
    volumes:
      - ./.docker/cas:/etc/cas/
    ports:
      - 8080:8080

  web:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'cas-mock-server'
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: >
      bash -c "EDITOR='cat' && bin/rails credentials:edit && bundle exec rails db:migrate db:truncate db:seed assets:precompile && bundle exec rails s -p 8020 -b 0.0.0.0"
    ports:
      - 8020:8020
    environment:
      RAILS_CAS_URL: http://cas-mock-server:8080/cas
      RAILS_DATABASE_URL: postgres://medplan:MyPassword@postgres/medplan_development
      RAILS_ENV: production
      RAILS_AUTHENTICATOR: cas_authenticatable
      RAILS_SERVE_STATIC_FILES: true
      RAILS_GROUP_MENU: true
      RAILS_REDIS_URL: redis://redis:6379/1
    links:
      - postgres
      - redis
      - cas-mock-server
