version: "3.7"
services:

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432

  redis:
    image: redis:alpine

  web:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'oidc-server-mock'
    build:
      context: .
      args:
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
    command: >
      bash -c "EDITOR='cat' && bin/rails credentials:edit && bundle exec rails db:migrate db:truncate db:seed assets:precompile && bundle exec rails s -p 8020 -b 0.0.0.0"
    ports:
      - 8020:8020
    environment:
      RAILS_OIDC_URL: ${RAILS_OIDC_URL}
      RAILS_DATABASE_URL: ${RAILS_DATABASE_URL}
      RAILS_ENV: ${RAILS_ENV}
      RAILS_AUTHENTICATOR: ${RAILS_AUTHENTICATOR}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
      RAILS_GROUP_MENU: ${RAILS_GROUP_MENU}
      RAILS_REDIS_URL: ${RAILS_REDIS_URL}
    links:
      - postgres
      - redis
  oidc-server-mock:
    container_name: oidc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:latest
    ports:
      - '4011:4011'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          },
          "Authentication": {
            "CookieSameSiteMode": "Lax",
            "CheckSessionCookieSameSiteMode": "Lax"
          }
        }
      LOGIN_OPTIONS_INLINE: |
        {
          "AllowRememberLogin": false
        }
      LOGOUT_OPTIONS_INLINE: |
        {
          "AutomaticRedirectAfterSignOut": true
        }
      API_SCOPES_INLINE: |
        - Name: some-app-scope-1
        - Name: some-app-scope-2
      API_RESOURCES_INLINE: |
        - Name: some-app
          Scopes:
            - some-app-scope-1
            - some-app-scope-2
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"1",
            "Username":"User1",
            "Password":"pwd",
            "Claims": [
              {
                "Type": "name",
                "Value": "Sam Tailor",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "sam.tailor@gmail.com",
                "ValueType": "string"
              },
              {
                "Type": "some-api-resource-claim",
                "Value": "Sam's Api Resource Custom Claim",
                "ValueType": "string"
              },
              {
                "Type": "some-api-scope-claim",
                "Value": "Sam's Api Scope Custom Claim",
                "ValueType": "string"
              },
              {
                "Type": "some-identity-resource-claim",
                "Value": "Sam's Identity Resource Custom Claim",
                "ValueType": "string"
              }
            ]
          }
        ]
      CLIENTS_CONFIGURATION_PATH: /tmp/config/clients-config.json
      ASPNET_SERVICES_OPTIONS_INLINE: |
        {
          "ForwardedHeadersOptions": {
            "ForwardedHeaders" : "All"
          }
        }
    volumes:
      - .:/tmp/config:ro