default: &default
  adapter: postgresql
  encoding: unicode
  schema_search_path: public
  pool: 5

development:
  <<: *default
  url: <%= ENV['RAILS_DATABASE_URL'] || Settings.database.development.url %>

test:
  <<: *default
  url: <%= ENV['RAILS_DATABASE_URL'] || Settings.database.test.url %>

staging:
  <<: *default
  url: <%= ENV['RAILS_DATABASE_URL'] || Settings.database.staging.url %>

production:
  <<: *default
  url: <%= ENV['RAILS_DATABASE_URL'] || Settings.database.production.url %>
