# frozen_string_literal: true


admin = User.new(username: 'admin', label: 'Administrator', name: 'Administrator', city: :other, cf: 'Admin1', admin: true)
admin.save(validate: false)
dottore = User.new(username: 'dottore', label: 'Dottore', name: 'Dottore', city: :roma, doctor: true, cf: 'DOTTORE1')
dottore.save(validate: false)
editor = User.new(username: 'editor', label: 'Editor', name: 'Eeditor', city: :roma, secretary: true, cf: 'SEGRETARIA1')
editor.save(validate: false)
mario = User.new(username: 'mario.rossi', label: 'Rossi Mario', name: 'Mario', lastname: 'Rossi', city: :roma, cf: 'RSSMRA69A01H501Z')
mario.save(validate: false)
utente = User.new(username: 'giorgio.verdi', label: 'Verdi Giorgio', name: 'Giorgio', lastname: 'Verdi', city: :venezia, cf: 'VRDGRG80A01L736Q')
utente.save(validate: false)
utente = User.new(username: 'grazia.bianchi', label: 'Bianchi Grazia', name: 'Grazia', lastname: 'Bianchi', cf: 'BNCGRZ63A41F205Z', city: :livorno)
utente.save(validate: false)

if Settings.auth.authenticator == 'database_authenticatable'
  admin.reset_password('admin','password')
  dottore.reset_password('dottore','password')
  editor.reset_password('editor','password')
  mario.reset_password('mario','password')
  utente.reset_password('giorgio','password')
  utente.reset_password('grazia','password')
end

if Rails.env.development?
  50.times do |n|
    u = User.create(username: "user#{n}", label: "User ##{n}", name: "User ##{n}", cf: "user#{n}", city: :other  ); u.save(validate: false)
  end
end

Category.create(code: 'cata', title: 'categoria a', months: 6)
Category.create(code: 'catb', title: 'categoria b', months: 12)
Category.create(code: '626chimici', title: 'chimici', months: 12)
Category.create(code: '626bio', title: 'biologi', months: 12)
Category.create(code: '626vdt', title: 'videoterminali', months: 24)
Category.create(code: '626guida', title: 'guida', months: 12)
Category.create(code: '626carichi', title: 'carichi', months: 12)
Category.create(code: '626copie', title: 'fotocopie', months: 12)
Category.create(code: 'richiamo', title: 'richiamo vaccinazione', months: 120)
Category.create(code: 'subacqueo', title: 'subacqueo', months: 12)
Category.create(code: 'snorkeling', title: 'snorkeling', months: 12)
Category.create(code: 'esterno', title: 'esterno', months: 12)
Category.create(code: 'patenteb', title: 'guida patente b', months: 12)
Category.create(code: 'patentec', title: 'guida patente c', months: 12)
Risk.create(code: '29', title: 'movimentazione manuale carichi')
Risk.create(code: '30', title: 'sovraccarico biomeccanico arti superiori')
Risk.create(code: '31', title: 'agenti chimici')
Risk.create(code: '32', title: 'agenti cancerogeni e mutageni')
Risk.create(code: '33', title: 'amianto')
Risk.create(code: '34', title: 'silice libera cristallina')
Risk.create(code: '35', title: 'agenti biologici')
Risk.create(code: '36', title: 'videoterminali')
Risk.create(code: '37', title: 'vibrazioni corpo intero')
Risk.create(code: '38', title: 'vibrazioni mano braccio')
Risk.create(code: '39', title: 'rumore')
Risk.create(code: '40', title: 'radiazioni ottiche artificiali')
Risk.create(code: '41', title: 'radiazioni ultraviolette naturali')
Risk.create(code: '42', title: 'microclima severo')
Risk.create(code: '43', title: 'infrasuoni')
Risk.create(code: '44', title: 'ultrasuoni')
Risk.create(code: '45', title: 'atmosfere iperbariche')
Risk.create(code: '46', title: 'lavoro notturno (d.lgs n.66 del 2003 2 2113/2004) >80gg/anno')
Risk.create(code: '47', title: 'altri rischi evidenziati da v.r.')
Risk.create(code: '48', title: 'guida patente b', printed: false)
Risk.create(code: '49', title: 'guida patente c', printed: false)
CategoryRisk.create(category_id: Category.where("code='626chimici'").first.id, risk_id: Risk.where("code='31'").first.id)
CategoryRisk.create(category_id: Category.where("code='626carichi'").first.id, risk_id: Risk.where("code='29'").first.id)
CategoryRisk.create(category_id: Category.where("code='626bio'").first.id, risk_id: Risk.where("code='35'").first.id)
CategoryRisk.create(category_id: Category.where("code='626vdt'").first.id, risk_id: Risk.where("code='36'").first.id)
CategoryRisk.create(category_id: Category.where("code='subacqueo'").first.id, risk_id: Risk.where("code='46'").first.id)
CategoryRisk.create(category_id: Category.where("code='626guida'").first.id, risk_id: Risk.where("code='47'").first.id)
CategoryRisk.create(category_id: Category.where("code='patenteb'").first.id, risk_id: Risk.where("code='48'").first.id)
CategoryRisk.create(category_id: Category.where("code='patentec'").first.id, risk_id: Risk.where("code='48'").first.id)
CategoryRisk.create(category_id: Category.where("code='patentec'").first.id, risk_id: Risk.where("code='49'").first.id)
